//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedBrick2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedBrick2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the selected part to a particular cutlist..
        /// </summary>
        internal static string AddPartHint {
            get {
                return ResourceManager.GetString("AddPartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the customer matches the project code in the filename..
        /// </summary>
        internal static string CustomerNotMatching {
            get {
                return ResourceManager.GetString("CustomerNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update will not apply Cutlist Material or Edging changes unless a cutlist is selected..
        /// </summary>
        internal static string CutlistNotSelectedWarning {
            get {
                return ResourceManager.GetString("CutlistNotSelectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimension from the cutlist database is {0}&quot;..
        /// </summary>
        internal static string DimensionNotMatch {
            get {
                return ResourceManager.GetString("DimensionNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should always confirm your edging after swapping dimensions..
        /// </summary>
        internal static string DimensionSwapWarning {
            get {
                return ResourceManager.GetString("DimensionSwapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edging is inconsistent with routing..
        /// </summary>
        internal static string InconsistentEdgingOp {
            get {
                return ResourceManager.GetString("InconsistentEdgingOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information in the Property Editor is in the database..
        /// </summary>
        internal static string InfoFromDB {
            get {
                return ResourceManager.GetString("InfoFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information in the Property Editor is NOT in the database. It was taken from the part..
        /// </summary>
        internal static string InfoNotFromDB {
            get {
                return ResourceManager.GetString("InfoNotFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert &apos;{0}&apos; into ECR# {1} items?.
        /// </summary>
        internal static string InsertIntoEcrItems {
            get {
                return ResourceManager.GetString("InsertIntoEcrItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary network resources are not available. Redbrick not starting..
        /// </summary>
        internal static string NetworkNotAvailable {
            get {
                return ResourceManager.GetString("NetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not classy to have no description..
        /// </summary>
        internal static string NoDescriptionWarning {
            get {
                return ResourceManager.GetString("NoDescriptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer greater than 0..
        /// </summary>
        internal static string NotNaturalNumberWarning {
            get {
                return ResourceManager.GetString("NotNaturalNumberWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type couldn&apos;t be figured out from property data..
        /// </summary>
        internal static string NoTypeWarning {
            get {
                return ResourceManager.GetString("NoTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust machine priority..
        /// </summary>
        internal static string PriorityHint {
            get {
                return ResourceManager.GetString("PriorityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redlego {
            get {
                object obj = ResourceManager.GetObject("redlego", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You probably don&apos;t want to mess with this..
        /// </summary>
        internal static string RegexHint {
            get {
                return ResourceManager.GetString("RegexHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected part from selected cutlist..
        /// </summary>
        internal static string RemoveHint {
            get {
                return ResourceManager.GetString("RemoveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the revision matches the revision indicated in the filename..
        /// </summary>
        internal static string RevisionNotMatching {
            get {
                return ResourceManager.GetString("RevisionNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setup {
            get {
                object obj = ResourceManager.GetObject("setup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stopwatch {
            get {
                object obj = ResourceManager.GetObject("stopwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material thickness doesn&apos;t match thickness dimension..
        /// </summary>
        internal static string ThicknessWarning {
            get {
                return ResourceManager.GetString("ThicknessWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust run/setup time..
        /// </summary>
        internal static string TimeHint {
            get {
                return ResourceManager.GetString("TimeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Editor {0}.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of the  Property Editor is out of date.   Do you want to update from {0} to {1}?.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Part/Assembly to the cutlist database..
        /// </summary>
        internal static string UpdateHint {
            get {
                return ResourceManager.GetString("UpdateHint", resourceCulture);
            }
        }
    }
}
